---
- name: Setup NGINX with SSL
  hosts: webservers
  become: true
  tasks:
    - name: Ensure NGINX is installed
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure NGINX service is running and enabled
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create SSL directory
      file:
        path: /etc/nginx/ssl
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: Generate self-signed SSL certificate and key
      command: openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout /etc/nginx/ssl/certificate.key -out /etc/nginx/ssl/certificate.crt

    - name: Copy the index.html file
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configure NGINX to use SSL
      template:
        src: templates/nginx_ssl.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Test NGINX configuration
      command: nginx -t
      notify: Restart NGINX

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
