Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
  
    # Use a bridged network
    config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)", ip: "192.168.1.10"
  
    config.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
    SHELL
  end
  